name: 'Release Helper'
description: 'A GitHub Action that help you publish release.'
author: 'xrkffgg'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  triger:
    description: 'How to start'
  token:
    description: 'Github token'
    default: ${{ github.token }}
  dingding-token:
    description: 'DingTalk token'
  dingding-msg:
    description: 'DingTalk message'
  prettier:
    description: 'DingTale message prettier'
  dingding-ignore:
    description: 'DingTalk ignore when version contain'
  branch:
    description: 'Branch'
  changelogs:
    description: 'Changelogs'
  draft:
    description: 'Release draft'
  prerelease:
    description: 'Release prerelease'
  prerelease-filter:
    description: 'Prerelease filter'
runs:
  using: node12
  main: 'dist/index.js'
