name: 'Release Helper'
description: 'A GitHub Action that help you publish release.'
author: 'xrkffgg'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  triger:
    description: 'How to start'
  token:
    description: 'Github token'
    default: ${{ github.token }}
  dingding-token:
    description: 'DingTalk token'
  dingding-msg:
    description: 'DingTalk message'
  dingding-delay-minute:
    description: 'DingTalk notice setTimeout'
  msg-title:
    description: 'message title'
  msg-head:
    description: 'message head'
  msg-poster:
    description: 'message poster'
  msg-footer:
    description: 'message footer'
  prettier:
    description: 'DingTale message prettier'
  dingding-ignore:
    description: 'DingTalk ignore when version contain'
  branch:
    description: 'Branch'
  changelogs:
    description: 'Changelogs'
  draft:
    description: 'Release draft'
  prerelease:
    description: 'Release prerelease'
  prerelease-filter:
    description: 'Prerelease filter'
  prerelease-notice:
    description: 'Prerelease notice'
  antd-conch-msg:
    description: 'Only for antd'
  release:
    description: 'Whether release'
runs:
  using: node12
  main: 'dist/index.js'
