name: 'Release Helper'
description: 'A GitHub Action that help you publish release.'
author: 'xrkffgg'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  actions:
    description: 'Action name'
  token:
    description: 'Github_token'
runs:
  using: node12
  main: 'dist/index.js'
